### ISSUE TITLE
Questionable Sentences

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-students/python-numbers-and-booleans-data-science-pilot#4]
"But you can move forward safely with just thinking of them as numbers and everything goes fine."

"goes" vs. "will go"
Starting both sentences with "But"

AND WHAT IS A BOOLEAN
A boolean is used to divide into two: True or False.

Weird title – I'd like a question mark.
That opening sentence seems like a weird explanation of booleans

**Comment by enummela** [comment]
Proposed fix: #8

**Comment by tkoar** [comment]
These have all been reworded and fixed on a branch and will be merged in.
